services:
  mariadb-backup:
    build:
      context: .
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/${BUILD_NAME}:${BUILD_VERSION}
    container_name: ${BUILD_NAME}
    hostname: ${BUILD_NAME}
    depends_on:
      - mariadb
      - etcd
      
  mariadb:
    image: ghcr.io/fvilarinho/mariadb:1.1.0
    container_name: mariadb
    hostname: mariadb
    ports:
      - "3306:3306"
    depends_on:
      - etcd

  etcd:
    image: ghcr.io/fvilarinho/etcd:1.1.0
    container_name: etcd
    hostname: etcd
    ports: 
      - "2379:2379"
    volumes:
      - ./etc/settings.json:/home/user/etc/${BUILD_NAME}.json
      - ../mariadb/etc/settings.json:/home/user/etc/mariadb.json
      - etcd-data:/home/user/data

volumes:
  etcd-data:
  