services:
  mariadb-backup:
    build:
      context: .
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/mariadb-backup:${BUILD_VERSION}
    container_name: mariadb-backup
    hostname: mariadb-backup
    depends_on:
      - mariadb
      - etcd
      
  mariadb:
    image: ghcr.io/fvilarinho/mariadb:1.1.0
    container_name: mariadb
    hostname: mariadb
    ports:
      - "3306:3306"
    depends_on:
      - etcd

  etcd:
    image: ghcr.io/fvilarinho/etcd:1.1.0
    container_name: etcd
    hostname: etcd
    ports: 
      - "2379:2379"
    volumes:
      - ./etc/settings.json:/home/user/etc/mariadb-backup.json
      - ../mariadb/etc/settings.json:/home/user/etc/mariadb.json
      - etcd-data:/home/user/data

volumes:
  etcd-data:
  