name: CI/CD

on:
  push:
    branches:
      - 'master'
      - 'develop'
    paths-ignore:
      - 'LICENSE'
      - '*.md'
      - '*.yml'
      
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Download project files
        uses: actions/checkout@v2

      - name: Build the Docker image
        env:
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: ./build.sh

      - name: Publish the Docker image
        env:
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: ./publish.sh
        